config/routes.rb
Rails.application.routes.draw do
  resources :checklists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "checklists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/checklist.rb
class Checklist < ApplicationRecord
    validates :item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :set_checklist, only: %i[ show edit update destroy ]

  # GET /checklists or /checklists.json
  def index
    @checklists = Checklist.all
  end

  # GET /checklists/1 or /checklists/1.json
  def show
  end

  # GET /checklists/new
  def new
    @checklist = Checklist.new
  end

  # GET /checklists/1/edit
  def edit
  end

  # POST /checklists or /checklists.json
  def create
    @checklist = Checklist.new(checklist_params)

    respond_to do |format|
      if @checklist.save
        format.html { redirect_to checklist_url(@checklist), notice: "Checklist was successfully created." }
        format.json { render :show, status: :created, location: @checklist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checklists/1 or /checklists/1.json
  def update
    respond_to do |format|
      if @checklist.update(checklist_params)
        format.html { redirect_to checklist_url(@checklist), notice: "Checklist was successfully updated." }
        format.json { render :show, status: :ok, location: @checklist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/1 or /checklists/1.json
  def destroy
    @checklist.destroy

    respond_to do |format|
      format.html { redirect_to checklists_url, notice: "Checklist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checklist
      @checklist = Checklist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def checklist_params
      params.require(:checklist).permit(:item, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_checklist.html.erb
<div id="<%= dom_id checklist %>">
  <p>
    <strong>Item:</strong>
    <%= checklist.item %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= checklist.completed %>
  </p>

</div>

app/views/checklists/_form.html.erb
<%= form_with(model: checklist) do |form| %>
  <% if checklist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(checklist.errors.count, "error") %> prohibited this checklist from being saved:</h2>

      <ul>
        <% checklist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item, style: "display: block" %>
    <%= form.text_field :item %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/checklists/edit.html.erb
<h1>Editing checklist</h1>

<%= render "form", checklist: @checklist %>

<br>

<div>
  <%= link_to "Show this checklist", @checklist %> |
  <%= link_to "Back to checklists", checklists_path %>
</div>

app/views/checklists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Checklists</h1>

<div id="checklists">
  <% @checklists.each do |checklist| %>
    <%= render checklist %>
    <p>
      <%= link_to "Show this checklist", checklist %>
    </p>
  <% end %>
</div>

<%= link_to "New checklist", new_checklist_path %>

app/views/checklists/new.html.erb
<h1>New checklist</h1>

<%= render "form", checklist: @checklist %>

<br>

<div>
  <%= link_to "Back to checklists", checklists_path %>
</div>

app/views/checklists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @checklist %>

<div>
  <%= link_to "Edit this checklist", edit_checklist_path(@checklist) %> |
  <%= link_to "Back to checklists", checklists_path %>

  <%= button_to "Destroy this checklist", @checklist, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>